version: '3'

services:
  mail-service:
    build:
      context: ./mail-service
      dockerfile: ./mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  sale-service:
    build:
      context: ./sale-service
      dockerfile: ./sale-service.dockerfile
    restart: always
    ports:
      - '8080:80'
      - '50001:50001'
    deploy:
      mode: replicated
      replicas: 1

  admin-service:
    build:
      context: ./admin-service
      dockerfile: ./admin-service.dockerfile
    restart: always
    ports:
      - '8081:80'
    deploy:
      mode: replicated
      replicas: 1

  rabbitmq:
    image: 'rabbitmq:3.9-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      mode: replicated
      replicas: 1
