version: '3'

services:
  mail-service:
    build:
      context: ./mail-service
      dockerfile: ./mail-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq

  sale-service:
    build:
      context: ./sale-service
      dockerfile: ./sale-service.dockerfile
    restart: always
    ports:
      - '8080:8080'
      - '50001:50001'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - GRPC_PORT=50001

  admin-service:
    build:
      context: ./admin-service
      dockerfile: ./admin-service.dockerfile
    restart: always
    ports:
      - '8081:8081'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - GRPC_URL=192.168.1.10:5001

  rabbitmq:
    image: 'rabbitmq:3.9-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    deploy:
      mode: replicated
      replicas: 1
